# fly.toml app configuration file generated for cashu-space-website on 2026-08-26T14:22:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cashu-space-website'
primary_region = 'ams'

[build]
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
